const allChamps = [
  {
    id: "Aatrox",
    key: "266",
    name: "아트",
    tags: ["Fighter", "Tank"],
    partype: "피의 샘",
    stats: {
      hp: 650,
      hpperlevel: 114,
      mp: 0,
      mpperlevel: 0,
      movespeed: 345,
      armor: 38,
      armorperlevel: 4.45,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 3,
      hpregenperlevel: 1,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 5,
      attackspeedperlevel: 2.5,
      attackspeed: 0.651,
    },
  },
  {
    id: "Ahri",
    key: "103",
    name: "아리",
    tags: ["Mage", "Assassin"],
    partype: "마나",
    stats: {
      hp: 590,
      hpperlevel: 96,
      mp: 418,
      mpperlevel: 25,
      movespeed: 330,
      armor: 21,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 2.5,
      hpregenperlevel: 0.6,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 53,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2,
      attackspeed: 0.668,
    },
  },
  {
    id: "Akali",
    key: "84",
    name: "아칼리",
    tags: ["Assassin"],
    partype: "기력",
    stats: {
      hp: 570,
      hpperlevel: 119,
      mp: 200,
      mpperlevel: 0,
      movespeed: 345,
      armor: 23,
      armorperlevel: 4.7,
      spellblock: 37,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 9,
      hpregenperlevel: 0.9,
      mpregen: 50,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 3.2,
      attackspeed: 0.625,
    },
  },
  {
    id: "Akshan",
    key: "166",
    name: "아크샨",
    tags: ["Marksman", "Assassin"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 107,
      mp: 350,
      mpperlevel: 40,
      movespeed: 330,
      armor: 26,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 3.75,
      hpregenperlevel: 0.65,
      mpregen: 8.2,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 52,
      attackdamageperlevel: 3,
      attackspeedperlevel: 4,
      attackspeed: 0.638,
    },
  },
  {
    id: "Alistar",
    key: "12",
    name: "알리스타",
    tags: ["Tank", "Support"],
    partype: "마나",
    stats: {
      hp: 685,
      hpperlevel: 120,
      mp: 350,
      mpperlevel: 40,
      movespeed: 330,
      armor: 47,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 0.85,
      mpregen: 8.5,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 3.75,
      attackspeedperlevel: 2.125,
      attackspeed: 0.625,
    },
  },
  {
    id: "Amumu",
    key: "32",
    name: "아무무",
    tags: ["Tank", "Mage"],
    partype: "마나",
    stats: {
      hp: 685,
      hpperlevel: 94,
      mp: 285,
      mpperlevel: 40,
      movespeed: 335,
      armor: 30,
      armorperlevel: 4,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 9,
      hpregenperlevel: 0.85,
      mpregen: 7.4,
      mpregenperlevel: 0.55,
      crit: 0,
      critperlevel: 0,
      attackdamage: 53,
      attackdamageperlevel: 3.8,
      attackspeedperlevel: 2.18,
      attackspeed: 0.736,
    },
  },
  {
    id: "Anivia",
    key: "34",
    name: "애니비아",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 550,
      hpperlevel: 92,
      mp: 495,
      mpperlevel: 45,
      movespeed: 325,
      armor: 21,
      armorperlevel: 4.9,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 600,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 51,
      attackdamageperlevel: 3.2,
      attackspeedperlevel: 1.68,
      attackspeed: 0.625,
    },
  },
  {
    id: "Annie",
    key: "1",
    name: "애니",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 560,
      hpperlevel: 102,
      mp: 418,
      mpperlevel: 25,
      movespeed: 335,
      armor: 19,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 625,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 50,
      attackdamageperlevel: 2.65,
      attackspeedperlevel: 1.36,
      attackspeed: 0.579,
    },
  },
  {
    id: "Aphelios",
    key: "523",
    name: "아펠",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 580,
      hpperlevel: 102,
      mp: 348,
      mpperlevel: 42,
      movespeed: 325,
      armor: 26,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 3.25,
      hpregenperlevel: 0.55,
      mpregen: 6.5,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.1,
      attackspeed: 0.64,
    },
  },
  {
    id: "Ashe",
    key: "22",
    name: "애쉬",
    tags: ["Marksman", "Support"],
    partype: "마나",
    stats: {
      hp: 640,
      hpperlevel: 101,
      mp: 280,
      mpperlevel: 35,
      movespeed: 325,
      armor: 26,
      armorperlevel: 4.6,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 600,
      hpregen: 3.5,
      hpregenperlevel: 0.55,
      mpregen: 7,
      mpregenperlevel: 0.65,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 2.95,
      attackspeedperlevel: 3.33,
      attackspeed: 0.658,
    },
  },
  {
    id: "AurelionSol",
    key: "136",
    name: "아우솔",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 620,
      hpperlevel: 90,
      mp: 530,
      mpperlevel: 40,
      movespeed: 335,
      armor: 22,
      armorperlevel: 4,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.75,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3.2,
      attackspeedperlevel: 1.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Azir",
    key: "268",
    name: "아지르",
    tags: ["Mage", "Marksman"],
    partype: "마나",
    stats: {
      hp: 550,
      hpperlevel: 119,
      mp: 320,
      mpperlevel: 40,
      movespeed: 335,
      armor: 22,
      armorperlevel: 5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 7,
      hpregenperlevel: 0.75,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 52,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 6,
      attackspeed: 0.625,
    },
  },
  {
    id: "Bard",
    key: "432",
    name: "바드",
    tags: ["Support", "Mage"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 103,
      mp: 350,
      mpperlevel: 50,
      movespeed: 330,
      armor: 34,
      armorperlevel: 5.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 6,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 52,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2,
      attackspeed: 0.625,
    },
  },
  {
    id: "Belveth",
    key: "200",
    name: "벨베스",
    tags: ["Fighter"],
    partype: "",
    stats: {
      hp: 610,
      hpperlevel: 99,
      mp: 60,
      mpperlevel: 0,
      movespeed: 340,
      armor: 32,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 6,
      hpregenperlevel: 0.6,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 1.5,
      attackspeedperlevel: 0,
      attackspeed: 0.85,
    },
  },
  {
    id: "Blitzcrank",
    key: "53",
    name: "블리츠",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 650,
      hpperlevel: 109,
      mp: 267,
      mpperlevel: 40,
      movespeed: 325,
      armor: 40,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 7.5,
      hpregenperlevel: 0.75,
      mpregen: 8.5,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 1.13,
      attackspeed: 0.625,
    },
  },
  {
    id: "Brand",
    key: "63",
    name: "브랜드",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 570,
      hpperlevel: 105,
      mp: 469,
      mpperlevel: 21,
      movespeed: 340,
      armor: 27,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 10.65,
      mpregenperlevel: 0.6,
      crit: 0,
      critperlevel: 0,
      attackdamage: 57,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2,
      attackspeed: 0.681,
    },
  },
  {
    id: "Braum",
    key: "201",
    name: "브라움",
    tags: ["Support", "Tank"],
    partype: "마나",
    stats: {
      hp: 610,
      hpperlevel: 112,
      mp: 311,
      mpperlevel: 45,
      movespeed: 335,
      armor: 47,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 1,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3.2,
      attackspeedperlevel: 3.5,
      attackspeed: 0.644,
    },
  },
  {
    id: "Briar",
    key: "233",
    name: "브라이어",
    tags: ["Fighter", "Assassin"],
    partype: "분노",
    stats: {
      hp: 610,
      hpperlevel: 100,
      mp: 0,
      mpperlevel: 0,
      movespeed: 340,
      armor: 32,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 0,
      hpregenperlevel: 0,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2,
      attackspeed: 0.644,
    },
  },
  {
    id: "Caitlyn",
    key: "51",
    name: "케이틀린",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 580,
      hpperlevel: 107,
      mp: 315,
      mpperlevel: 40,
      movespeed: 325,
      armor: 27,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 650,
      hpregen: 3.5,
      hpregenperlevel: 0.55,
      mpregen: 7.4,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 3.8,
      attackspeedperlevel: 4,
      attackspeed: 0.681,
    },
  },
  {
    id: "Camille",
    key: "164",
    name: "카밀",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 646,
      hpperlevel: 99,
      mp: 339,
      mpperlevel: 52,
      movespeed: 340,
      armor: 35,
      armorperlevel: 5,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 0.8,
      mpregen: 8.15,
      mpregenperlevel: 0.75,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 3.8,
      attackspeedperlevel: 2.5,
      attackspeed: 0.644,
    },
  },
  {
    id: "Cassiopeia",
    key: "69",
    name: "카시",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 104,
      mp: 350,
      mpperlevel: 60,
      movespeed: 328,
      armor: 18,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.5,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 53,
      attackdamageperlevel: 3,
      attackspeedperlevel: 1.5,
      attackspeed: 0.647,
    },
  },
  {
    id: "Chogath",
    key: "31",
    name: "초가스",
    tags: ["Tank", "Mage"],
    partype: "마나",
    stats: {
      hp: 644,
      hpperlevel: 94,
      mp: 270,
      mpperlevel: 60,
      movespeed: 345,
      armor: 38,
      armorperlevel: 5,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 9,
      hpregenperlevel: 0.85,
      mpregen: 7.2,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 69,
      attackdamageperlevel: 4.2,
      attackspeedperlevel: 1.44,
      attackspeed: 0.625,
    },
  },
  {
    id: "Corki",
    key: "42",
    name: "코르키",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 588,
      hpperlevel: 105,
      mp: 350,
      mpperlevel: 54,
      movespeed: 325,
      armor: 28,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 7.4,
      mpregenperlevel: 0.55,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 2.8,
      attackspeedperlevel: 2.3,
      attackspeed: 0.638,
    },
  },
  {
    id: "Darius",
    key: "122",
    name: "다리우스",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 652,
      hpperlevel: 114,
      mp: 263,
      mpperlevel: 58,
      movespeed: 340,
      armor: 39,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 10,
      hpregenperlevel: 0.95,
      mpregen: 6.6,
      mpregenperlevel: 0.35,
      crit: 0,
      critperlevel: 0,
      attackdamage: 64,
      attackdamageperlevel: 5,
      attackspeedperlevel: 1,
      attackspeed: 0.625,
    },
  },
  {
    id: "Diana",
    key: "131",
    name: "다이애나",
    tags: ["Fighter", "Mage"],
    partype: "마나",
    stats: {
      hp: 640,
      hpperlevel: 109,
      mp: 375,
      mpperlevel: 25,
      movespeed: 345,
      armor: 31,
      armorperlevel: 4.3,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 150,
      hpregen: 6.5,
      hpregenperlevel: 0.85,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 57,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.25,
      attackspeed: 0.625,
    },
  },
  {
    id: "Draven",
    key: "119",
    name: "드레이븐",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 675,
      hpperlevel: 104,
      mp: 361,
      mpperlevel: 39,
      movespeed: 330,
      armor: 29,
      armorperlevel: 4.5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 3.75,
      hpregenperlevel: 0.7,
      mpregen: 8.05,
      mpregenperlevel: 0.65,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 3.6,
      attackspeedperlevel: 2.7,
      attackspeed: 0.679,
    },
  },
  {
    id: "DrMundo",
    key: "36",
    name: "문도",
    tags: ["Fighter", "Tank"],
    partype: "없음",
    stats: {
      hp: 613,
      hpperlevel: 103,
      mp: 0,
      mpperlevel: 0,
      movespeed: 345,
      armor: 32,
      armorperlevel: 3.7,
      spellblock: 29,
      spellblockperlevel: 2.3,
      attackrange: 125,
      hpregen: 7,
      hpregenperlevel: 0.5,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61,
      attackdamageperlevel: 2.5,
      attackspeedperlevel: 3.3,
      attackspeed: 0.67,
    },
  },
  {
    id: "Ekko",
    key: "245",
    name: "에코",
    tags: ["Assassin", "Fighter"],
    partype: "마나",
    stats: {
      hp: 655,
      hpperlevel: 99,
      mp: 280,
      mpperlevel: 70,
      movespeed: 340,
      armor: 32,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 9,
      hpregenperlevel: 0.9,
      mpregen: 7,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3.3,
      attackspeed: 0.688,
    },
  },
  {
    id: "Elise",
    key: "60",
    name: "엘리스",
    tags: ["Mage", "Fighter"],
    partype: "마나",
    stats: {
      hp: 650,
      hpperlevel: 109,
      mp: 324,
      mpperlevel: 50,
      movespeed: 330,
      armor: 30,
      armorperlevel: 5.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.6,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3,
      attackspeedperlevel: 1.75,
      attackspeed: 0.625,
    },
  },
  {
    id: "Evelynn",
    key: "28",
    name: "이블린",
    tags: ["Assassin", "Mage"],
    partype: "마나",
    stats: {
      hp: 642,
      hpperlevel: 98,
      mp: 315,
      mpperlevel: 42,
      movespeed: 335,
      armor: 37,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 0.75,
      mpregen: 8.11,
      mpregenperlevel: 0.6,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.1,
      attackspeed: 0.667,
    },
  },
  {
    id: "Ezreal",
    key: "81",
    name: "이즈",
    tags: ["Marksman", "Mage"],
    partype: "마나",
    stats: {
      hp: 600,
      hpperlevel: 102,
      mp: 375,
      mpperlevel: 70,
      movespeed: 325,
      armor: 24,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 4,
      hpregenperlevel: 0.65,
      mpregen: 8.5,
      mpregenperlevel: 1,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 2.5,
      attackspeedperlevel: 2.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Fiddlesticks",
    key: "9",
    name: "피들",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 650,
      hpperlevel: 106,
      mp: 500,
      mpperlevel: 28,
      movespeed: 335,
      armor: 34,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 480,
      hpregen: 5.5,
      hpregenperlevel: 0.6,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 2.65,
      attackspeedperlevel: 2.11,
      attackspeed: 0.625,
    },
  },
  {
    id: "Fiora",
    key: "114",
    name: "피오라",
    tags: ["Fighter", "Assassin"],
    partype: "마나",
    stats: {
      hp: 620,
      hpperlevel: 99,
      mp: 300,
      mpperlevel: 60,
      movespeed: 345,
      armor: 33,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 150,
      hpregen: 8.5,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 3.2,
      attackspeed: 0.69,
    },
  },
  {
    id: "Fizz",
    key: "105",
    name: "피즈",
    tags: ["Assassin", "Fighter"],
    partype: "마나",
    stats: {
      hp: 640,
      hpperlevel: 106,
      mp: 317,
      mpperlevel: 52,
      movespeed: 335,
      armor: 22,
      armorperlevel: 4.6,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 8,
      hpregenperlevel: 0.7,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3.1,
      attackspeed: 0.658,
    },
  },
  {
    id: "Galio",
    key: "3",
    name: "갈리오",
    tags: ["Tank", "Mage"],
    partype: "마나",
    stats: {
      hp: 632,
      hpperlevel: 126,
      mp: 500,
      mpperlevel: 40,
      movespeed: 335,
      armor: 24,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 150,
      hpregen: 8,
      hpregenperlevel: 0.8,
      mpregen: 9.5,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 1.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Gangplank",
    key: "41",
    name: "갱플",
    tags: ["Fighter"],
    partype: "마나",
    stats: {
      hp: 600,
      hpperlevel: 114,
      mp: 280,
      mpperlevel: 60,
      movespeed: 345,
      armor: 31,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 6,
      hpregenperlevel: 0.6,
      mpregen: 7.5,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 64,
      attackdamageperlevel: 3.7,
      attackspeedperlevel: 3.2,
      attackspeed: 0.658,
    },
  },
  {
    id: "Garen",
    key: "86",
    name: "가렌",
    tags: ["Fighter", "Tank"],
    partype: "없음",
    stats: {
      hp: 690,
      hpperlevel: 98,
      mp: 0,
      mpperlevel: 0,
      movespeed: 340,
      armor: 38,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 1.55,
      attackrange: 175,
      hpregen: 8,
      hpregenperlevel: 0.5,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 69,
      attackdamageperlevel: 4.5,
      attackspeedperlevel: 3.65,
      attackspeed: 0.625,
    },
  },
  {
    id: "Gnar",
    key: "150",
    name: "나르",
    tags: ["Fighter", "Tank"],
    partype: "분노",
    stats: {
      hp: 540,
      hpperlevel: 79,
      mp: 100,
      mpperlevel: 0,
      movespeed: 335,
      armor: 32,
      armorperlevel: 3.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 175,
      hpregen: 4.5,
      hpregenperlevel: 1.25,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 57,
      attackdamageperlevel: 3,
      attackspeedperlevel: 6,
      attackspeed: 0.625,
    },
  },
  {
    id: "Gragas",
    key: "79",
    name: "그라",
    tags: ["Fighter", "Mage"],
    partype: "마나",
    stats: {
      hp: 670,
      hpperlevel: 109,
      mp: 400,
      mpperlevel: 47,
      movespeed: 330,
      armor: 38,
      armorperlevel: 4.8,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 5.5,
      hpregenperlevel: 0.5,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 64,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 2.05,
      attackspeed: 0.675,
    },
  },
  {
    id: "Graves",
    key: "104",
    name: "그브",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 625,
      hpperlevel: 106,
      mp: 325,
      mpperlevel: 40,
      movespeed: 340,
      armor: 33,
      armorperlevel: 4.6,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 425,
      hpregen: 8,
      hpregenperlevel: 0.7,
      mpregen: 8,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 4,
      attackspeedperlevel: 2.6,
      attackspeed: 0.475,
    },
  },
  {
    id: "Gwen",
    key: "887",
    name: "그웬",
    tags: ["Fighter", "Assassin"],
    partype: "마나",
    stats: {
      hp: 620,
      hpperlevel: 115,
      mp: 330,
      mpperlevel: 40,
      movespeed: 340,
      armor: 39,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 150,
      hpregen: 9,
      hpregenperlevel: 0.9,
      mpregen: 7.5,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 63,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.25,
      attackspeed: 0.69,
    },
  },
  {
    id: "Hecarim",
    key: "120",
    name: "헤카림",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 625,
      hpperlevel: 99,
      mp: 280,
      mpperlevel: 40,
      movespeed: 345,
      armor: 32,
      armorperlevel: 5.45,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 7,
      hpregenperlevel: 0.75,
      mpregen: 7,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 66,
      attackdamageperlevel: 3.7,
      attackspeedperlevel: 2.5,
      attackspeed: 0.67,
    },
  },
  {
    id: "Heimerdinger",
    key: "74",
    name: "딩거",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 558,
      hpperlevel: 101,
      mp: 385,
      mpperlevel: 20,
      movespeed: 340,
      armor: 19,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 7,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 56,
      attackdamageperlevel: 2.7,
      attackspeedperlevel: 1.36,
      attackspeed: 0.625,
    },
  },
  {
    id: "Illaoi",
    key: "420",
    name: "일라",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 656,
      hpperlevel: 109,
      mp: 300,
      mpperlevel: 50,
      movespeed: 350,
      armor: 35,
      armorperlevel: 5,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 9.5,
      hpregenperlevel: 0.8,
      mpregen: 7.5,
      mpregenperlevel: 0.75,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 5,
      attackspeedperlevel: 2.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Irelia",
    key: "39",
    name: "이렐",
    tags: ["Fighter", "Assassin"],
    partype: "마나",
    stats: {
      hp: 590,
      hpperlevel: 124,
      mp: 350,
      mpperlevel: 50,
      movespeed: 335,
      armor: 36,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 2.05,
      attackrange: 200,
      hpregen: 8.5,
      hpregenperlevel: 0.85,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 65,
      attackdamageperlevel: 4,
      attackspeedperlevel: 2.5,
      attackspeed: 0.656,
    },
  },
  {
    id: "Ivern",
    key: "427",
    name: "아이번",
    tags: ["Support", "Mage"],
    partype: "마나",
    stats: {
      hp: 655,
      hpperlevel: 99,
      mp: 450,
      mpperlevel: 60,
      movespeed: 330,
      armor: 27,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 475,
      hpregen: 7,
      hpregenperlevel: 0.85,
      mpregen: 6,
      mpregenperlevel: 0.75,
      crit: 0,
      critperlevel: 0,
      attackdamage: 50,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3.4,
      attackspeed: 0.644,
    },
  },
  {
    id: "Janna",
    key: "40",
    name: "잔나",
    tags: ["Support", "Mage"],
    partype: "마나",
    stats: {
      hp: 570,
      hpperlevel: 84,
      mp: 350,
      mpperlevel: 64,
      movespeed: 325,
      armor: 28,
      armorperlevel: 5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 11.5,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 52,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3,
      attackspeed: 0.625,
    },
  },
  {
    id: "JarvanIV",
    key: "59",
    name: "자르반",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 640,
      hpperlevel: 104,
      mp: 300,
      mpperlevel: 55,
      movespeed: 340,
      armor: 36,
      armorperlevel: 4.8,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 8,
      hpregenperlevel: 0.7,
      mpregen: 6.5,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 64,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.5,
      attackspeed: 0.658,
    },
  },
  {
    id: "Jax",
    key: "24",
    name: "잭스",
    tags: ["Fighter", "Assassin"],
    partype: "마나",
    stats: {
      hp: 665,
      hpperlevel: 100,
      mp: 339,
      mpperlevel: 52,
      movespeed: 350,
      armor: 36,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 0.55,
      mpregen: 7.6,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 4.25,
      attackspeedperlevel: 3.4,
      attackspeed: 0.638,
    },
  },
  {
    id: "Jayce",
    key: "126",
    name: "제이스",
    tags: ["Fighter", "Marksman"],
    partype: "마나",
    stats: {
      hp: 590,
      hpperlevel: 109,
      mp: 375,
      mpperlevel: 45,
      movespeed: 335,
      armor: 22,
      armorperlevel: 5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 125,
      hpregen: 6,
      hpregenperlevel: 0.6,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 57,
      attackdamageperlevel: 4.25,
      attackspeedperlevel: 3,
      attackspeed: 0.658,
    },
  },
  {
    id: "Jhin",
    key: "202",
    name: "진",
    tags: ["Marksman", "Mage"],
    partype: "마나",
    stats: {
      hp: 655,
      hpperlevel: 107,
      mp: 300,
      mpperlevel: 50,
      movespeed: 330,
      armor: 24,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 3.75,
      hpregenperlevel: 0.55,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 4.7,
      attackspeedperlevel: 0,
      attackspeed: 0.625,
    },
  },
  {
    id: "Jinx",
    key: "222",
    name: "징크스",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 105,
      mp: 260,
      mpperlevel: 50,
      movespeed: 325,
      armor: 26,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 3.75,
      hpregenperlevel: 0.5,
      mpregen: 6.7,
      mpregenperlevel: 1,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 3.15,
      attackspeedperlevel: 1,
      attackspeed: 0.625,
    },
  },
  {
    id: "Kaisa",
    key: "145",
    name: "카이사",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 640,
      hpperlevel: 102,
      mp: 345,
      mpperlevel: 40,
      movespeed: 335,
      armor: 25,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 3.5,
      hpregenperlevel: 0.55,
      mpregen: 8.2,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 2.6,
      attackspeedperlevel: 1.8,
      attackspeed: 0.644,
    },
  },
  {
    id: "Kalista",
    key: "429",
    name: "칼리",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 600,
      hpperlevel: 114,
      mp: 300,
      mpperlevel: 45,
      movespeed: 330,
      armor: 24,
      armorperlevel: 5.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 4,
      hpregenperlevel: 0.75,
      mpregen: 6.3,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61,
      attackdamageperlevel: 3.25,
      attackspeedperlevel: 4.5,
      attackspeed: 0.694,
    },
  },
  {
    id: "Karma",
    key: "43",
    name: "카르마",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 604,
      hpperlevel: 109,
      mp: 374,
      mpperlevel: 50,
      movespeed: 335,
      armor: 28,
      armorperlevel: 5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 13,
      mpregenperlevel: 0.5,
      crit: 0,
      critperlevel: 0,
      attackdamage: 51,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 2.3,
      attackspeed: 0.625,
    },
  },
  {
    id: "Karthus",
    key: "30",
    name: "카서스",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 620,
      hpperlevel: 110,
      mp: 467,
      mpperlevel: 31,
      movespeed: 335,
      armor: 21,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 450,
      hpregen: 6.5,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 46,
      attackdamageperlevel: 3.25,
      attackspeedperlevel: 2.11,
      attackspeed: 0.625,
    },
  },
  {
    id: "Kassadin",
    key: "38",
    name: "카사딘",
    tags: ["Assassin", "Mage"],
    partype: "마나",
    stats: {
      hp: 646,
      hpperlevel: 119,
      mp: 400,
      mpperlevel: 87,
      movespeed: 335,
      armor: 19,
      armorperlevel: 4,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 150,
      hpregen: 6,
      hpregenperlevel: 0.5,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 3.9,
      attackspeedperlevel: 3.7,
      attackspeed: 0.64,
    },
  },
  {
    id: "Katarina",
    key: "55",
    name: "카타",
    tags: ["Assassin", "Mage"],
    partype: "없음",
    stats: {
      hp: 672,
      hpperlevel: 108,
      mp: 0,
      mpperlevel: 0,
      movespeed: 335,
      armor: 28,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 7.5,
      hpregenperlevel: 0.7,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 3.2,
      attackspeedperlevel: 2.74,
      attackspeed: 0.658,
    },
  },
  {
    id: "Kayle",
    key: "10",
    name: "케일",
    tags: ["Fighter", "Support"],
    partype: "마나",
    stats: {
      hp: 670,
      hpperlevel: 92,
      mp: 330,
      mpperlevel: 50,
      movespeed: 335,
      armor: 26,
      armorperlevel: 4.2,
      spellblock: 22,
      spellblockperlevel: 1.3,
      attackrange: 175,
      hpregen: 5,
      hpregenperlevel: 0.5,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 50,
      attackdamageperlevel: 2.5,
      attackspeedperlevel: 1.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Kayn",
    key: "141",
    name: "케인",
    tags: ["Fighter", "Assassin"],
    partype: "마나",
    stats: {
      hp: 655,
      hpperlevel: 109,
      mp: 410,
      mpperlevel: 50,
      movespeed: 340,
      armor: 38,
      armorperlevel: 4.5,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 8,
      hpregenperlevel: 0.75,
      mpregen: 11.5,
      mpregenperlevel: 0.95,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 2.7,
      attackspeed: 0.669,
    },
  },
  {
    id: "Kennen",
    key: "85",
    name: "케넨",
    tags: ["Mage", "Marksman"],
    partype: "기력",
    stats: {
      hp: 611,
      hpperlevel: 98,
      mp: 200,
      mpperlevel: 0,
      movespeed: 335,
      armor: 29,
      armorperlevel: 4.95,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.65,
      mpregen: 50,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 48,
      attackdamageperlevel: 3.75,
      attackspeedperlevel: 3.4,
      attackspeed: 0.625,
    },
  },
  {
    id: "Khazix",
    key: "121",
    name: "카직스",
    tags: ["Assassin"],
    partype: "마나",
    stats: {
      hp: 643,
      hpperlevel: 99,
      mp: 327,
      mpperlevel: 40,
      movespeed: 350,
      armor: 36,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 7.5,
      hpregenperlevel: 0.75,
      mpregen: 7.59,
      mpregenperlevel: 0.5,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 3.1,
      attackspeedperlevel: 2.7,
      attackspeed: 0.668,
    },
  },
  {
    id: "Kindred",
    key: "203",
    name: "킨드",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 610,
      hpperlevel: 104,
      mp: 300,
      mpperlevel: 35,
      movespeed: 325,
      armor: 29,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 7,
      hpregenperlevel: 0.55,
      mpregen: 7,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 65,
      attackdamageperlevel: 3.25,
      attackspeedperlevel: 3.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Kled",
    key: "240",
    name: "클레드",
    tags: ["Fighter", "Tank"],
    partype: "용기",
    stats: {
      hp: 410,
      hpperlevel: 84,
      mp: 100,
      mpperlevel: 0,
      movespeed: 345,
      armor: 35,
      armorperlevel: 5.2,
      spellblock: 28,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 6,
      hpregenperlevel: 0.75,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 65,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 3.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "KogMaw",
    key: "96",
    name: "코그모",
    tags: ["Marksman", "Mage"],
    partype: "마나",
    stats: {
      hp: 635,
      hpperlevel: 99,
      mp: 325,
      mpperlevel: 40,
      movespeed: 330,
      armor: 24,
      armorperlevel: 4.45,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 3.75,
      hpregenperlevel: 0.55,
      mpregen: 8.75,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61,
      attackdamageperlevel: 3.1,
      attackspeedperlevel: 2.65,
      attackspeed: 0.665,
    },
  },
  {
    id: "KSante",
    key: "897",
    name: "크산테",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 570,
      hpperlevel: 115,
      mp: 290,
      mpperlevel: 60,
      movespeed: 330,
      armor: 33,
      armorperlevel: 5.2,
      spellblock: 30,
      spellblockperlevel: 2.1,
      attackrange: 175,
      hpregen: 9.5,
      hpregenperlevel: 0.85,
      mpregen: 7,
      mpregenperlevel: 1,
      crit: 0,
      critperlevel: 0,
      attackdamage: 64,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 2.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Leblanc",
    key: "7",
    name: "르블랑",
    tags: ["Assassin", "Mage"],
    partype: "마나",
    stats: {
      hp: 598,
      hpperlevel: 111,
      mp: 400,
      mpperlevel: 25,
      movespeed: 340,
      armor: 22,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 7.5,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 2.7,
      attackspeedperlevel: 2.2,
      attackspeed: 0.625,
    },
  },
  {
    id: "LeeSin",
    key: "64",
    name: "리신",
    tags: ["Fighter", "Assassin"],
    partype: "기력",
    stats: {
      hp: 645,
      hpperlevel: 105,
      mp: 200,
      mpperlevel: 0,
      movespeed: 345,
      armor: 36,
      armorperlevel: 4.9,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 7.5,
      hpregenperlevel: 0.7,
      mpregen: 50,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 66,
      attackdamageperlevel: 3.7,
      attackspeedperlevel: 3,
      attackspeed: 0.651,
    },
  },
  {
    id: "Leona",
    key: "89",
    name: "레오나",
    tags: ["Tank", "Support"],
    partype: "마나",
    stats: {
      hp: 646,
      hpperlevel: 101,
      mp: 302,
      mpperlevel: 40,
      movespeed: 335,
      armor: 47,
      armorperlevel: 4.8,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 0.85,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.9,
      attackspeed: 0.625,
    },
  },
  {
    id: "Lillia",
    key: "876",
    name: "릴리아",
    tags: ["Fighter", "Mage"],
    partype: "마나",
    stats: {
      hp: 605,
      hpperlevel: 105,
      mp: 410,
      mpperlevel: 50,
      movespeed: 330,
      armor: 22,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 1.55,
      attackrange: 325,
      hpregen: 2.5,
      hpregenperlevel: 0.55,
      mpregen: 11.5,
      mpregenperlevel: 0.95,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61,
      attackdamageperlevel: 3.1,
      attackspeedperlevel: 2.7,
      attackspeed: 0.625,
    },
  },
  {
    id: "Lissandra",
    key: "127",
    name: "리산",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 620,
      hpperlevel: 110,
      mp: 475,
      mpperlevel: 30,
      movespeed: 325,
      armor: 22,
      armorperlevel: 4.9,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 7,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 2.7,
      attackspeedperlevel: 1.36,
      attackspeed: 0.656,
    },
  },
  {
    id: "Lucian",
    key: "236",
    name: "루시안",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 641,
      hpperlevel: 100,
      mp: 320,
      mpperlevel: 43,
      movespeed: 335,
      armor: 28,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 3.75,
      hpregenperlevel: 0.65,
      mpregen: 7,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 2.9,
      attackspeedperlevel: 3.3,
      attackspeed: 0.638,
    },
  },
  {
    id: "Lulu",
    key: "117",
    name: "룰루",
    tags: ["Support", "Mage"],
    partype: "마나",
    stats: {
      hp: 595,
      hpperlevel: 92,
      mp: 350,
      mpperlevel: 55,
      movespeed: 330,
      armor: 26,
      armorperlevel: 4.9,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 6,
      hpregenperlevel: 0.6,
      mpregen: 11,
      mpregenperlevel: 0.6,
      crit: 0,
      critperlevel: 0,
      attackdamage: 47,
      attackdamageperlevel: 2.6,
      attackspeedperlevel: 2.25,
      attackspeed: 0.625,
    },
  },
  {
    id: "Lux",
    key: "99",
    name: "럭스",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 560,
      hpperlevel: 99,
      mp: 480,
      mpperlevel: 23.5,
      movespeed: 330,
      armor: 19,
      armorperlevel: 5.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 7,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 54,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 2,
      attackspeed: 0.669,
    },
  },
  {
    id: "Malphite",
    key: "54",
    name: "말파",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 644,
      hpperlevel: 104,
      mp: 280,
      mpperlevel: 60,
      movespeed: 335,
      armor: 37,
      armorperlevel: 4.95,
      spellblock: 28,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 7,
      hpregenperlevel: 0.55,
      mpregen: 7.3,
      mpregenperlevel: 0.55,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 4,
      attackspeedperlevel: 3.4,
      attackspeed: 0.736,
    },
  },
  {
    id: "Malzahar",
    key: "90",
    name: "말자하",
    tags: ["Mage", "Assassin"],
    partype: "마나",
    stats: {
      hp: 580,
      hpperlevel: 101,
      mp: 375,
      mpperlevel: 28,
      movespeed: 335,
      armor: 18,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 6,
      hpregenperlevel: 0.6,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3,
      attackspeedperlevel: 1.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Maokai",
    key: "57",
    name: "마오카이",
    tags: ["Tank", "Mage"],
    partype: "마나",
    stats: {
      hp: 635,
      hpperlevel: 109,
      mp: 375,
      mpperlevel: 43,
      movespeed: 335,
      armor: 39,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 5,
      hpregenperlevel: 0.75,
      mpregen: 7.2,
      mpregenperlevel: 0.6,
      crit: 0,
      critperlevel: 0,
      attackdamage: 64,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 2.125,
      attackspeed: 0.8,
    },
  },
  {
    id: "MasterYi",
    key: "11",
    name: "마이",
    tags: ["Assassin", "Fighter"],
    partype: "마나",
    stats: {
      hp: 669,
      hpperlevel: 100,
      mp: 251,
      mpperlevel: 42,
      movespeed: 355,
      armor: 33,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 7.5,
      hpregenperlevel: 0.65,
      mpregen: 7.25,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 65,
      attackdamageperlevel: 2.2,
      attackspeedperlevel: 2,
      attackspeed: 0.679,
    },
  },
  {
    id: "Milio",
    key: "902",
    name: "밀리오",
    tags: ["Support"],
    partype: "마나",
    stats: {
      hp: 560,
      hpperlevel: 88,
      mp: 365,
      mpperlevel: 43,
      movespeed: 330,
      armor: 26,
      armorperlevel: 4.6,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 5,
      hpregenperlevel: 0.5,
      mpregen: 11.5,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 48,
      attackdamageperlevel: 3.2,
      attackspeedperlevel: 3,
      attackspeed: 0.625,
    },
  },
  {
    id: "MissFortune",
    key: "21",
    name: "미포",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 640,
      hpperlevel: 103,
      mp: 300,
      mpperlevel: 40,
      movespeed: 325,
      armor: 28,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 3.75,
      hpregenperlevel: 0.65,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 52,
      attackdamageperlevel: 2.4,
      attackspeedperlevel: 3,
      attackspeed: 0.656,
    },
  },
  {
    id: "MonkeyKing",
    key: "62",
    name: "오공",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 610,
      hpperlevel: 99,
      mp: 300,
      mpperlevel: 65,
      movespeed: 340,
      armor: 31,
      armorperlevel: 4.7,
      spellblock: 28,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 3.5,
      hpregenperlevel: 0.65,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 66,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 3,
      attackspeed: 0.69,
    },
  },
  {
    id: "Mordekaiser",
    key: "82",
    name: "모데",
    tags: ["Fighter"],
    partype: "보호막 ",
    stats: {
      hp: 645,
      hpperlevel: 104,
      mp: 100,
      mpperlevel: 0,
      movespeed: 335,
      armor: 37,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 5,
      hpregenperlevel: 0.75,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61,
      attackdamageperlevel: 4,
      attackspeedperlevel: 1,
      attackspeed: 0.625,
    },
  },
  {
    id: "Morgana",
    key: "25",
    name: "모르가나",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 104,
      mp: 340,
      mpperlevel: 60,
      movespeed: 335,
      armor: 25,
      armorperlevel: 5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 450,
      hpregen: 5.5,
      hpregenperlevel: 0.4,
      mpregen: 11,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 56,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 1.53,
      attackspeed: 0.625,
    },
  },
  {
    id: "Naafiri",
    key: "950",
    name: "나피리",
    tags: ["Assassin"],
    partype: "마나",
    stats: {
      hp: 635,
      hpperlevel: 120,
      mp: 400,
      mpperlevel: 55,
      movespeed: 335,
      armor: 30,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 9,
      hpregenperlevel: 0.9,
      mpregen: 7.5,
      mpregenperlevel: 1,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 2.1,
      attackspeedperlevel: 2.1,
      attackspeed: 0.663,
    },
  },
  {
    id: "Nami",
    key: "267",
    name: "나미",
    tags: ["Support", "Mage"],
    partype: "마나",
    stats: {
      hp: 560,
      hpperlevel: 88,
      mp: 365,
      mpperlevel: 43,
      movespeed: 335,
      armor: 29,
      armorperlevel: 5.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 11.5,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 51,
      attackdamageperlevel: 3.1,
      attackspeedperlevel: 2.61,
      attackspeed: 0.644,
    },
  },
  {
    id: "Nasus",
    key: "75",
    name: "나서스",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 631,
      hpperlevel: 104,
      mp: 326,
      mpperlevel: 62,
      movespeed: 350,
      armor: 34,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 9,
      hpregenperlevel: 0.9,
      mpregen: 7.45,
      mpregenperlevel: 0.5,
      crit: 0,
      critperlevel: 0,
      attackdamage: 67,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 3.48,
      attackspeed: 0.638,
    },
  },
  {
    id: "Nautilus",
    key: "111",
    name: "노틸",
    tags: ["Tank", "Support"],
    partype: "마나",
    stats: {
      hp: 646,
      hpperlevel: 100,
      mp: 400,
      mpperlevel: 47,
      movespeed: 325,
      armor: 39,
      armorperlevel: 4.95,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 8.5,
      hpregenperlevel: 0.55,
      mpregen: 8.65,
      mpregenperlevel: 0.5,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 1,
      attackspeed: 0.706,
    },
  },
  {
    id: "Neeko",
    key: "518",
    name: "니코",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 610,
      hpperlevel: 104,
      mp: 450,
      mpperlevel: 30,
      movespeed: 340,
      armor: 21,
      armorperlevel: 5.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 7.5,
      hpregenperlevel: 0.75,
      mpregen: 7,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 48,
      attackdamageperlevel: 2.5,
      attackspeedperlevel: 3.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Nidalee",
    key: "76",
    name: "니달리",
    tags: ["Assassin", "Mage"],
    partype: "마나",
    stats: {
      hp: 610,
      hpperlevel: 109,
      mp: 295,
      mpperlevel: 45,
      movespeed: 340,
      armor: 32,
      armorperlevel: 5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 6,
      hpregenperlevel: 0.6,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 3.22,
      attackspeed: 0.638,
    },
  },
  {
    id: "Nilah",
    key: "895",
    name: "닐라",
    tags: ["Fighter", "Assassin"],
    partype: "마나",
    stats: {
      hp: 570,
      hpperlevel: 101,
      mp: 350,
      mpperlevel: 35,
      movespeed: 340,
      armor: 27,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 225,
      hpregen: 4,
      hpregenperlevel: 0.9,
      mpregen: 8.2,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 2,
      attackspeedperlevel: 3,
      attackspeed: 0.697,
    },
  },
  {
    id: "Nocturne",
    key: "56",
    name: "녹턴",
    tags: ["Assassin", "Fighter"],
    partype: "마나",
    stats: {
      hp: 655,
      hpperlevel: 109,
      mp: 275,
      mpperlevel: 35,
      movespeed: 345,
      armor: 38,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 1.55,
      attackrange: 125,
      hpregen: 7,
      hpregenperlevel: 0.75,
      mpregen: 7,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 2.6,
      attackspeedperlevel: 2.7,
      attackspeed: 0.721,
    },
  },
  {
    id: "Nunu",
    key: "20",
    name: "누누",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 610,
      hpperlevel: 90,
      mp: 280,
      mpperlevel: 42,
      movespeed: 345,
      armor: 29,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 5,
      hpregenperlevel: 0.8,
      mpregen: 7,
      mpregenperlevel: 0.5,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.25,
      attackspeed: 0.625,
    },
  },
  {
    id: "Olaf",
    key: "2",
    name: "올라프",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 645,
      hpperlevel: 119,
      mp: 316,
      mpperlevel: 50,
      movespeed: 350,
      armor: 35,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 6.5,
      hpregenperlevel: 0.6,
      mpregen: 7.5,
      mpregenperlevel: 0.6,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 4.7,
      attackspeedperlevel: 2.7,
      attackspeed: 0.694,
    },
  },
  {
    id: "Orianna",
    key: "61",
    name: "오리",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 600,
      hpperlevel: 110,
      mp: 418,
      mpperlevel: 25,
      movespeed: 325,
      armor: 20,
      armorperlevel: 4.2,
      spellblock: 26,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 7,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 40,
      attackdamageperlevel: 2.6,
      attackspeedperlevel: 3.5,
      attackspeed: 0.658,
    },
  },
  {
    id: "Ornn",
    key: "516",
    name: "오른",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 660,
      hpperlevel: 109,
      mp: 341,
      mpperlevel: 65,
      movespeed: 335,
      armor: 33,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 9,
      hpregenperlevel: 0.9,
      mpregen: 8,
      mpregenperlevel: 0.6,
      crit: 0,
      critperlevel: 0,
      attackdamage: 69,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 2,
      attackspeed: 0.625,
    },
  },
  {
    id: "Pantheon",
    key: "80",
    name: "판테",
    tags: ["Fighter", "Assassin"],
    partype: "마나",
    stats: {
      hp: 650,
      hpperlevel: 109,
      mp: 317,
      mpperlevel: 31,
      movespeed: 345,
      armor: 40,
      armorperlevel: 4.95,
      spellblock: 28,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 6,
      hpregenperlevel: 0.65,
      mpregen: 7.35,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 64,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 2.95,
      attackspeed: 0.658,
    },
  },
  {
    id: "Poppy",
    key: "78",
    name: "뽀삐",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 610,
      hpperlevel: 104,
      mp: 280,
      mpperlevel: 40,
      movespeed: 345,
      armor: 38,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8,
      hpregenperlevel: 0.8,
      mpregen: 7,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 64,
      attackdamageperlevel: 4,
      attackspeedperlevel: 2.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Pyke",
    key: "555",
    name: "파이크",
    tags: ["Support", "Assassin"],
    partype: "마나",
    stats: {
      hp: 670,
      hpperlevel: 110,
      mp: 415,
      mpperlevel: 50,
      movespeed: 330,
      armor: 45,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 150,
      hpregen: 7,
      hpregenperlevel: 0.5,
      mpregen: 8,
      mpregenperlevel: 1,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 2,
      attackspeedperlevel: 2.5,
      attackspeed: 0.667,
    },
  },
  {
    id: "Qiyana",
    key: "246",
    name: "키아나",
    tags: ["Assassin", "Fighter"],
    partype: "마나",
    stats: {
      hp: 590,
      hpperlevel: 124,
      mp: 320,
      mpperlevel: 50,
      movespeed: 335,
      armor: 28,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 150,
      hpregen: 6,
      hpregenperlevel: 0.9,
      mpregen: 8,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 66,
      attackdamageperlevel: 3.1,
      attackspeedperlevel: 2.1,
      attackspeed: 0.688,
    },
  },
  {
    id: "Quinn",
    key: "133",
    name: "퀸",
    tags: ["Marksman", "Assassin"],
    partype: "마나",
    stats: {
      hp: 565,
      hpperlevel: 107,
      mp: 269,
      mpperlevel: 35,
      movespeed: 330,
      armor: 28,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 7,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 2.7,
      attackspeedperlevel: 3.1,
      attackspeed: 0.668,
    },
  },
  {
    id: "Rakan",
    key: "497",
    name: "라칸",
    tags: ["Support"],
    partype: "마나",
    stats: {
      hp: 610,
      hpperlevel: 99,
      mp: 315,
      mpperlevel: 50,
      movespeed: 335,
      armor: 30,
      armorperlevel: 4.9,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 300,
      hpregen: 5,
      hpregenperlevel: 0.5,
      mpregen: 8.75,
      mpregenperlevel: 0.5,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 3,
      attackspeed: 0.635,
    },
  },
  {
    id: "Rammus",
    key: "33",
    name: "람머스",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 675,
      hpperlevel: 94,
      mp: 310,
      mpperlevel: 33,
      movespeed: 335,
      armor: 40,
      armorperlevel: 5.5,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8,
      hpregenperlevel: 0.55,
      mpregen: 7.85,
      mpregenperlevel: 0.5,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 2.75,
      attackspeedperlevel: 2.215,
      attackspeed: 0.656,
    },
  },
  {
    id: "RekSai",
    key: "421",
    name: "렉사이",
    tags: ["Fighter"],
    partype: "분노",
    stats: {
      hp: 600,
      hpperlevel: 99,
      mp: 100,
      mpperlevel: 0,
      movespeed: 335,
      armor: 36,
      armorperlevel: 4.95,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 7.5,
      hpregenperlevel: 0.65,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2,
      attackspeed: 0.667,
    },
  },
  {
    id: "Rell",
    key: "526",
    name: "렐",
    tags: ["Tank", "Support"],
    partype: "마나",
    stats: {
      hp: 610,
      hpperlevel: 104,
      mp: 350,
      mpperlevel: 45,
      movespeed: 330,
      armor: 36,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.85,
      attackrange: 175,
      hpregen: 7.5,
      hpregenperlevel: 0.85,
      mpregen: 6,
      mpregenperlevel: 0.35,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3,
      attackspeedperlevel: 1.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Renata",
    key: "888",
    name: "레나타",
    tags: ["Support", "Mage"],
    partype: "마나",
    stats: {
      hp: 545,
      hpperlevel: 94,
      mp: 350,
      mpperlevel: 50,
      movespeed: 330,
      armor: 27,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 11.5,
      mpregenperlevel: 0.5,
      crit: 0,
      critperlevel: 0,
      attackdamage: 49,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.11,
      attackspeed: 0.625,
    },
  },
  {
    id: "Renekton",
    key: "58",
    name: "레넥톤",
    tags: ["Fighter", "Tank"],
    partype: "분노",
    stats: {
      hp: 660,
      hpperlevel: 111,
      mp: 100,
      mpperlevel: 0,
      movespeed: 345,
      armor: 35,
      armorperlevel: 5.2,
      spellblock: 28,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8,
      hpregenperlevel: 0.75,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 69,
      attackdamageperlevel: 4.15,
      attackspeedperlevel: 2.75,
      attackspeed: 0.665,
    },
  },
  {
    id: "Rengar",
    key: "107",
    name: "렝가",
    tags: ["Assassin", "Fighter"],
    partype: "흉포",
    stats: {
      hp: 620,
      hpperlevel: 104,
      mp: 4,
      mpperlevel: 0,
      movespeed: 345,
      armor: 34,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 6,
      hpregenperlevel: 0.5,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3,
      attackspeed: 0.667,
    },
  },
  {
    id: "Riven",
    key: "92",
    name: "리븐",
    tags: ["Fighter", "Assassin"],
    partype: "없음",
    stats: {
      hp: 630,
      hpperlevel: 100,
      mp: 0,
      mpperlevel: 0,
      movespeed: 340,
      armor: 33,
      armorperlevel: 4.4,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 0.5,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 64,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Rumble",
    key: "68",
    name: "럼블",
    tags: ["Fighter", "Mage"],
    partype: "열기",
    stats: {
      hp: 625,
      hpperlevel: 105,
      mp: 150,
      mpperlevel: 0,
      movespeed: 345,
      armor: 36,
      armorperlevel: 4.7,
      spellblock: 28,
      spellblockperlevel: 1.55,
      attackrange: 125,
      hpregen: 7,
      hpregenperlevel: 0.6,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61,
      attackdamageperlevel: 3.2,
      attackspeedperlevel: 1.85,
      attackspeed: 0.644,
    },
  },
  {
    id: "Ryze",
    key: "13",
    name: "라이즈",
    tags: ["Mage", "Fighter"],
    partype: "마나",
    stats: {
      hp: 645,
      hpperlevel: 124,
      mp: 300,
      mpperlevel: 70,
      movespeed: 340,
      armor: 22,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 8,
      hpregenperlevel: 0.8,
      mpregen: 8,
      mpregenperlevel: 1,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.11,
      attackspeed: 0.625,
    },
  },
  {
    id: "Samira",
    key: "360",
    name: "사미라",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 108,
      mp: 349,
      mpperlevel: 38,
      movespeed: 335,
      armor: 26,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 3.25,
      hpregenperlevel: 0.55,
      mpregen: 8.2,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 57,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 3.3,
      attackspeed: 0.658,
    },
  },
  {
    id: "Sejuani",
    key: "113",
    name: "세주",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 114,
      mp: 400,
      mpperlevel: 40,
      movespeed: 340,
      armor: 34,
      armorperlevel: 5.45,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 150,
      hpregen: 8.5,
      hpregenperlevel: 1,
      mpregen: 7,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 66,
      attackdamageperlevel: 4,
      attackspeedperlevel: 3.5,
      attackspeed: 0.688,
    },
  },
  {
    id: "Senna",
    key: "235",
    name: "세나",
    tags: ["Marksman", "Support"],
    partype: "마나",
    stats: {
      hp: 530,
      hpperlevel: 89,
      mp: 350,
      mpperlevel: 45,
      movespeed: 330,
      armor: 28,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 600,
      hpregen: 3.5,
      hpregenperlevel: 0.55,
      mpregen: 11.5,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 50,
      attackdamageperlevel: 0,
      attackspeedperlevel: 4,
      attackspeed: 0.625,
    },
  },
  {
    id: "Seraphine",
    key: "147",
    name: "세라핀",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 570,
      hpperlevel: 90,
      mp: 360,
      mpperlevel: 50,
      movespeed: 325,
      armor: 26,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 6.5,
      hpregenperlevel: 0.6,
      mpregen: 11.5,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2,
      attackspeed: 0.669,
    },
  },
  {
    id: "Sett",
    key: "875",
    name: "세트",
    tags: ["Fighter", "Tank"],
    partype: "투지",
    stats: {
      hp: 670,
      hpperlevel: 114,
      mp: 0,
      mpperlevel: 0,
      movespeed: 340,
      armor: 33,
      armorperlevel: 5.2,
      spellblock: 28,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 7,
      hpregenperlevel: 0.5,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 4,
      attackspeedperlevel: 1.75,
      attackspeed: 0.625,
    },
  },
  {
    id: "Shaco",
    key: "35",
    name: "샤코",
    tags: ["Assassin"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 99,
      mp: 297,
      mpperlevel: 40,
      movespeed: 345,
      armor: 30,
      armorperlevel: 4,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 0.55,
      mpregen: 6,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 63,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3,
      attackspeed: 0.694,
    },
  },
  {
    id: "Shen",
    key: "98",
    name: "쉔",
    tags: ["Tank"],
    partype: "기력",
    stats: {
      hp: 610,
      hpperlevel: 99,
      mp: 400,
      mpperlevel: 0,
      movespeed: 340,
      armor: 34,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 0.75,
      mpregen: 50,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3,
      attackspeed: 0.751,
    },
  },
  {
    id: "Shyvana",
    key: "102",
    name: "쉬바나",
    tags: ["Fighter", "Tank"],
    partype: "분노",
    stats: {
      hp: 665,
      hpperlevel: 104,
      mp: 100,
      mpperlevel: 0,
      movespeed: 350,
      armor: 38,
      armorperlevel: 4.55,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 0.8,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 66,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.5,
      attackspeed: 0.658,
    },
  },
  {
    id: "Singed",
    key: "27",
    name: "신지드",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 650,
      hpperlevel: 99,
      mp: 330,
      mpperlevel: 45,
      movespeed: 345,
      armor: 34,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 9.5,
      hpregenperlevel: 0.55,
      mpregen: 7.5,
      mpregenperlevel: 0.55,
      crit: 0,
      critperlevel: 0,
      attackdamage: 63,
      attackdamageperlevel: 3.4,
      attackspeedperlevel: 1.9,
      attackspeed: 0.613,
    },
  },
  {
    id: "Sion",
    key: "14",
    name: "사이온",
    tags: ["Tank", "Fighter"],
    partype: "마나",
    stats: {
      hp: 655,
      hpperlevel: 87,
      mp: 400,
      mpperlevel: 52,
      movespeed: 345,
      armor: 32,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 7.5,
      hpregenperlevel: 0.8,
      mpregen: 8,
      mpregenperlevel: 0.6,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 4,
      attackspeedperlevel: 1.3,
      attackspeed: 0.679,
    },
  },
  {
    id: "Sivir",
    key: "15",
    name: "시비르",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 600,
      hpperlevel: 104,
      mp: 340,
      mpperlevel: 45,
      movespeed: 335,
      armor: 26,
      armorperlevel: 4.45,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 3.25,
      hpregenperlevel: 0.55,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 2.5,
      attackspeedperlevel: 2,
      attackspeed: 0.625,
    },
  },
  {
    id: "Skarner",
    key: "72",
    name: "스카너",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 650,
      hpperlevel: 99,
      mp: 320,
      mpperlevel: 60,
      movespeed: 335,
      armor: 38,
      armorperlevel: 5,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 9,
      hpregenperlevel: 0.85,
      mpregen: 7.2,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 65,
      attackdamageperlevel: 4.5,
      attackspeedperlevel: 2.1,
      attackspeed: 0.625,
    },
  },
  {
    id: "Sona",
    key: "37",
    name: "소나",
    tags: ["Support", "Mage"],
    partype: "마나",
    stats: {
      hp: 550,
      hpperlevel: 91,
      mp: 340,
      mpperlevel: 45,
      movespeed: 325,
      armor: 26,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 11.5,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 49,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.3,
      attackspeed: 0.644,
    },
  },
  {
    id: "Soraka",
    key: "16",
    name: "소라카",
    tags: ["Support", "Mage"],
    partype: "마나",
    stats: {
      hp: 605,
      hpperlevel: 88,
      mp: 425,
      mpperlevel: 40,
      movespeed: 325,
      armor: 32,
      armorperlevel: 5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 2.5,
      hpregenperlevel: 0.5,
      mpregen: 11.5,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 50,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.14,
      attackspeed: 0.625,
    },
  },
  {
    id: "Swain",
    key: "50",
    name: "스웨인",
    tags: ["Mage", "Fighter"],
    partype: "마나",
    stats: {
      hp: 595,
      hpperlevel: 99,
      mp: 468,
      mpperlevel: 29,
      movespeed: 330,
      armor: 26,
      armorperlevel: 5.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 7,
      hpregenperlevel: 0.65,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 2.7,
      attackspeedperlevel: 2.11,
      attackspeed: 0.625,
    },
  },
  {
    id: "Sylas",
    key: "517",
    name: "사일러스",
    tags: ["Mage", "Assassin"],
    partype: "마나",
    stats: {
      hp: 575,
      hpperlevel: 129,
      mp: 400,
      mpperlevel: 70,
      movespeed: 340,
      armor: 27,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 2.55,
      attackrange: 175,
      hpregen: 9,
      hpregenperlevel: 0.9,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3.5,
      attackspeed: 0.645,
    },
  },
  {
    id: "Syndra",
    key: "134",
    name: "신드라",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 563,
      hpperlevel: 104,
      mp: 480,
      mpperlevel: 40,
      movespeed: 330,
      armor: 25,
      armorperlevel: 4.6,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 6.5,
      hpregenperlevel: 0.6,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 54,
      attackdamageperlevel: 2.9,
      attackspeedperlevel: 2,
      attackspeed: 0.625,
    },
  },
  {
    id: "TahmKench",
    key: "223",
    name: "탐켄치",
    tags: ["Support", "Tank"],
    partype: "마나",
    stats: {
      hp: 640,
      hpperlevel: 103,
      mp: 325,
      mpperlevel: 50,
      movespeed: 335,
      armor: 42,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 6.5,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 1,
      crit: 0,
      critperlevel: 0,
      attackdamage: 56,
      attackdamageperlevel: 3.2,
      attackspeedperlevel: 2.5,
      attackspeed: 0.658,
    },
  },
  {
    id: "Taliyah",
    key: "163",
    name: "탈리야",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 550,
      hpperlevel: 104,
      mp: 470,
      mpperlevel: 30,
      movespeed: 330,
      armor: 18,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 6.5,
      hpregenperlevel: 0.65,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 1.36,
      attackspeed: 0.625,
    },
  },
  {
    id: "Talon",
    key: "91",
    name: "탈론",
    tags: ["Assassin"],
    partype: "마나",
    stats: {
      hp: 658,
      hpperlevel: 109,
      mp: 400,
      mpperlevel: 37,
      movespeed: 335,
      armor: 30,
      armorperlevel: 4.7,
      spellblock: 39,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 8.5,
      hpregenperlevel: 0.75,
      mpregen: 7.6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 3.1,
      attackspeedperlevel: 2.9,
      attackspeed: 0.625,
    },
  },
  {
    id: "Taric",
    key: "44",
    name: "타릭",
    tags: ["Support", "Fighter"],
    partype: "마나",
    stats: {
      hp: 645,
      hpperlevel: 99,
      mp: 300,
      mpperlevel: 60,
      movespeed: 340,
      armor: 40,
      armorperlevel: 4.6,
      spellblock: 28,
      spellblockperlevel: 2.05,
      attackrange: 150,
      hpregen: 6,
      hpregenperlevel: 0.5,
      mpregen: 8.5,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 2,
      attackspeed: 0.625,
    },
  },
  {
    id: "Teemo",
    key: "17",
    name: "티모",
    tags: ["Marksman", "Assassin"],
    partype: "마나",
    stats: {
      hp: 598,
      hpperlevel: 104,
      mp: 334,
      mpperlevel: 25,
      movespeed: 330,
      armor: 24,
      armorperlevel: 4.95,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 5.5,
      hpregenperlevel: 0.65,
      mpregen: 9.6,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 54,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3.38,
      attackspeed: 0.69,
    },
  },
  {
    id: "Thresh",
    key: "412",
    name: "쓰레쉬",
    tags: ["Support", "Fighter"],
    partype: "마나",
    stats: {
      hp: 600,
      hpperlevel: 120,
      mp: 274,
      mpperlevel: 44,
      movespeed: 330,
      armor: 28,
      armorperlevel: 0,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 450,
      hpregen: 7,
      hpregenperlevel: 0.55,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 56,
      attackdamageperlevel: 2.2,
      attackspeedperlevel: 3.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Tristana",
    key: "18",
    name: "트타",
    tags: ["Marksman", "Assassin"],
    partype: "마나",
    stats: {
      hp: 640,
      hpperlevel: 102,
      mp: 250,
      mpperlevel: 32,
      movespeed: 325,
      armor: 30,
      armorperlevel: 4.5,
      spellblock: 28,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 4,
      hpregenperlevel: 0.65,
      mpregen: 7.2,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 3.7,
      attackspeedperlevel: 1.5,
      attackspeed: 0.656,
    },
  },
  {
    id: "Trundle",
    key: "48",
    name: "트런들",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 686,
      hpperlevel: 110,
      mp: 340,
      mpperlevel: 45,
      movespeed: 350,
      armor: 37,
      armorperlevel: 3.9,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 6,
      hpregenperlevel: 0.75,
      mpregen: 7.5,
      mpregenperlevel: 0.6,
      crit: 0,
      critperlevel: 0,
      attackdamage: 68,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.9,
      attackspeed: 0.67,
    },
  },
  {
    id: "Tryndamere",
    key: "23",
    name: "트린",
    tags: ["Fighter", "Assassin"],
    partype: "분노",
    stats: {
      hp: 696,
      hpperlevel: 108,
      mp: 100,
      mpperlevel: 0,
      movespeed: 345,
      armor: 33,
      armorperlevel: 4.3,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 8.5,
      hpregenperlevel: 0.9,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 66,
      attackdamageperlevel: 4,
      attackspeedperlevel: 2.9,
      attackspeed: 0.67,
    },
  },
  {
    id: "TwistedFate",
    key: "4",
    name: "트페",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 604,
      hpperlevel: 108,
      mp: 333,
      mpperlevel: 39,
      movespeed: 330,
      armor: 21,
      armorperlevel: 4.35,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 5.5,
      hpregenperlevel: 0.6,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 52,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 3.22,
      attackspeed: 0.651,
    },
  },
  {
    id: "Twitch",
    key: "29",
    name: "트위치",
    tags: ["Marksman", "Assassin"],
    partype: "마나",
    stats: {
      hp: 682,
      hpperlevel: 100,
      mp: 300,
      mpperlevel: 40,
      movespeed: 330,
      armor: 27,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 3.75,
      hpregenperlevel: 0.6,
      mpregen: 7.25,
      mpregenperlevel: 0.7,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 3.1,
      attackspeedperlevel: 3.38,
      attackspeed: 0.679,
    },
  },
  {
    id: "Udyr",
    key: "77",
    name: "우디르",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 664,
      hpperlevel: 92,
      mp: 271,
      mpperlevel: 50,
      movespeed: 350,
      armor: 31,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 6,
      hpregenperlevel: 0.75,
      mpregen: 7.5,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 4,
      attackspeedperlevel: 3,
      attackspeed: 0.65,
    },
  },
  {
    id: "Urgot",
    key: "6",
    name: "우르곳",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 655,
      hpperlevel: 102,
      mp: 340,
      mpperlevel: 45,
      movespeed: 330,
      armor: 36,
      armorperlevel: 5.45,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 350,
      hpregen: 7.5,
      hpregenperlevel: 0.7,
      mpregen: 7.25,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 63,
      attackdamageperlevel: 4,
      attackspeedperlevel: 3.75,
      attackspeed: 0.625,
    },
  },
  {
    id: "Varus",
    key: "110",
    name: "바루스",
    tags: ["Marksman", "Mage"],
    partype: "마나",
    stats: {
      hp: 600,
      hpperlevel: 105,
      mp: 360,
      mpperlevel: 40,
      movespeed: 330,
      armor: 27,
      armorperlevel: 4.6,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 575,
      hpregen: 3.5,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 3.4,
      attackspeedperlevel: 4,
      attackspeed: 0.658,
    },
  },
  {
    id: "Vayne",
    key: "67",
    name: "베인",
    tags: ["Marksman", "Assassin"],
    partype: "마나",
    stats: {
      hp: 550,
      hpperlevel: 103,
      mp: 232,
      mpperlevel: 35,
      movespeed: 330,
      armor: 23,
      armorperlevel: 4.6,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 3.5,
      hpregenperlevel: 0.55,
      mpregen: 7,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 2.35,
      attackspeedperlevel: 3.3,
      attackspeed: 0.658,
    },
  },
  {
    id: "Veigar",
    key: "45",
    name: "베이가",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 550,
      hpperlevel: 108,
      mp: 490,
      mpperlevel: 26,
      movespeed: 340,
      armor: 18,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 6.5,
      hpregenperlevel: 0.6,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 52,
      attackdamageperlevel: 2.7,
      attackspeedperlevel: 2.24,
      attackspeed: 0.625,
    },
  },
  {
    id: "Velkoz",
    key: "161",
    name: "벨코즈",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 590,
      hpperlevel: 102,
      mp: 469,
      mpperlevel: 21,
      movespeed: 340,
      armor: 22,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3.1416,
      attackspeedperlevel: 1.36,
      attackspeed: 0.625,
    },
  },
  {
    id: "Vex",
    key: "711",
    name: "벡스",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 590,
      hpperlevel: 104,
      mp: 490,
      mpperlevel: 32,
      movespeed: 335,
      armor: 23,
      armorperlevel: 4.45,
      spellblock: 28,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 6.5,
      hpregenperlevel: 0.6,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 54,
      attackdamageperlevel: 2.75,
      attackspeedperlevel: 1,
      attackspeed: 0.669,
    },
  },
  {
    id: "Vi",
    key: "254",
    name: "바이",
    tags: ["Fighter", "Assassin"],
    partype: "마나",
    stats: {
      hp: 655,
      hpperlevel: 99,
      mp: 295,
      mpperlevel: 65,
      movespeed: 340,
      armor: 30,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 10,
      hpregenperlevel: 1,
      mpregen: 8,
      mpregenperlevel: 0.65,
      crit: 0,
      critperlevel: 0,
      attackdamage: 63,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2,
      attackspeed: 0.644,
    },
  },
  {
    id: "Viego",
    key: "234",
    name: "비에고",
    tags: ["Assassin", "Fighter"],
    partype: "없음",
    stats: {
      hp: 630,
      hpperlevel: 109,
      mp: 10000,
      mpperlevel: 0,
      movespeed: 345,
      armor: 34,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 200,
      hpregen: 7,
      hpregenperlevel: 0.7,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 57,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 2.5,
      attackspeed: 0.658,
    },
  },
  {
    id: "Viktor",
    key: "112",
    name: "빅토르",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 600,
      hpperlevel: 104,
      mp: 405,
      mpperlevel: 45,
      movespeed: 335,
      armor: 23,
      armorperlevel: 5.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 8,
      hpregenperlevel: 0.65,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 53,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.11,
      attackspeed: 0.658,
    },
  },
  {
    id: "Vladimir",
    key: "8",
    name: "블라디",
    tags: ["Mage"],
    partype: "핏빛 격노",
    stats: {
      hp: 607,
      hpperlevel: 110,
      mp: 2,
      mpperlevel: 0,
      movespeed: 330,
      armor: 27,
      armorperlevel: 4.5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 450,
      hpregen: 7,
      hpregenperlevel: 0.6,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2,
      attackspeed: 0.658,
    },
  },
  {
    id: "Volibear",
    key: "106",
    name: "볼베",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 650,
      hpperlevel: 104,
      mp: 350,
      mpperlevel: 70,
      movespeed: 340,
      armor: 31,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 150,
      hpregen: 9,
      hpregenperlevel: 0.75,
      mpregen: 6.25,
      mpregenperlevel: 0.5,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 2,
      attackspeed: 0.625,
    },
  },
  {
    id: "Warwick",
    key: "19",
    name: "워윅",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 620,
      hpperlevel: 99,
      mp: 280,
      mpperlevel: 35,
      movespeed: 335,
      armor: 33,
      armorperlevel: 4.4,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 4,
      hpregenperlevel: 0.75,
      mpregen: 7.45,
      mpregenperlevel: 0.6,
      crit: 0,
      critperlevel: 0,
      attackdamage: 65,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.3,
      attackspeed: 0.638,
    },
  },
  {
    id: "Xayah",
    key: "498",
    name: "자야",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 107,
      mp: 340,
      mpperlevel: 40,
      movespeed: 330,
      armor: 25,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 3.25,
      hpregenperlevel: 0.75,
      mpregen: 8.25,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 3.5,
      attackspeedperlevel: 3.9,
      attackspeed: 0.658,
    },
  },
  {
    id: "Xerath",
    key: "101",
    name: "제라스",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 596,
      hpperlevel: 106,
      mp: 400,
      mpperlevel: 22,
      movespeed: 340,
      armor: 22,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 6.85,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 55,
      attackdamageperlevel: 3,
      attackspeedperlevel: 1.36,
      attackspeed: 0.625,
    },
  },
  {
    id: "XinZhao",
    key: "5",
    name: "짜오",
    tags: ["Fighter", "Assassin"],
    partype: "마나",
    stats: {
      hp: 640,
      hpperlevel: 106,
      mp: 274,
      mpperlevel: 55,
      movespeed: 345,
      armor: 35,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 8,
      hpregenperlevel: 0.7,
      mpregen: 7.25,
      mpregenperlevel: 0.45,
      crit: 0,
      critperlevel: 0,
      attackdamage: 63,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3.5,
      attackspeed: 0.645,
    },
  },
  {
    id: "Yasuo",
    key: "157",
    name: "야스오",
    tags: ["Fighter", "Assassin"],
    partype: "기류",
    stats: {
      hp: 590,
      hpperlevel: 110,
      mp: 100,
      mpperlevel: 0,
      movespeed: 345,
      armor: 30,
      armorperlevel: 4.6,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 6.5,
      hpregenperlevel: 0.9,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3.5,
      attackspeed: 0.697,
    },
  },
  {
    id: "Yone",
    key: "777",
    name: "요네",
    tags: ["Assassin", "Fighter"],
    partype: "기류",
    stats: {
      hp: 620,
      hpperlevel: 105,
      mp: 500,
      mpperlevel: 0,
      movespeed: 345,
      armor: 30,
      armorperlevel: 4.6,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 7.5,
      hpregenperlevel: 0.75,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 2,
      attackspeedperlevel: 3.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Yorick",
    key: "83",
    name: "요릭",
    tags: ["Fighter", "Tank"],
    partype: "마나",
    stats: {
      hp: 650,
      hpperlevel: 114,
      mp: 300,
      mpperlevel: 60,
      movespeed: 340,
      armor: 39,
      armorperlevel: 5.2,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 8,
      hpregenperlevel: 0.8,
      mpregen: 7.5,
      mpregenperlevel: 0.75,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 5,
      attackspeedperlevel: 2,
      attackspeed: 0.625,
    },
  },
  {
    id: "Yuumi",
    key: "350",
    name: "유미",
    tags: ["Support", "Mage"],
    partype: "마나",
    stats: {
      hp: 500,
      hpperlevel: 69,
      mp: 440,
      mpperlevel: 45,
      movespeed: 330,
      armor: 25,
      armorperlevel: 4.2,
      spellblock: 25,
      spellblockperlevel: 1.1,
      attackrange: 425,
      hpregen: 5,
      hpregenperlevel: 0.55,
      mpregen: 10,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 49,
      attackdamageperlevel: 3.1,
      attackspeedperlevel: 1,
      attackspeed: 0.625,
    },
  },
  {
    id: "Zac",
    key: "154",
    name: "자크",
    tags: ["Tank", "Fighter"],
    partype: "없음",
    stats: {
      hp: 685,
      hpperlevel: 109,
      mp: 0,
      mpperlevel: 0,
      movespeed: 340,
      armor: 33,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 8,
      hpregenperlevel: 0.5,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60,
      attackdamageperlevel: 3.4,
      attackspeedperlevel: 1.6,
      attackspeed: 0.736,
    },
  },
  {
    id: "Zed",
    key: "238",
    name: "제드",
    tags: ["Assassin"],
    partype: "기력",
    stats: {
      hp: 654,
      hpperlevel: 99,
      mp: 200,
      mpperlevel: 0,
      movespeed: 345,
      armor: 32,
      armorperlevel: 4.7,
      spellblock: 29,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 7,
      hpregenperlevel: 0.65,
      mpregen: 50,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 63,
      attackdamageperlevel: 3.4,
      attackspeedperlevel: 3.3,
      attackspeed: 0.651,
    },
  },
  {
    id: "Zeri",
    key: "221",
    name: "제리",
    tags: ["Marksman"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 110,
      mp: 250,
      mpperlevel: 45,
      movespeed: 330,
      armor: 24,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 3.25,
      hpregenperlevel: 0.7,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 53,
      attackdamageperlevel: 1.3,
      attackspeedperlevel: 2,
      attackspeed: 0.658,
    },
  },
  {
    id: "Ziggs",
    key: "115",
    name: "직스",
    tags: ["Mage"],
    partype: "마나",
    stats: {
      hp: 606,
      hpperlevel: 106,
      mp: 480,
      mpperlevel: 23.5,
      movespeed: 325,
      armor: 22,
      armorperlevel: 4.5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 6.5,
      hpregenperlevel: 0.6,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 54,
      attackdamageperlevel: 3.1,
      attackspeedperlevel: 2,
      attackspeed: 0.656,
    },
  },
  {
    id: "Zilean",
    key: "26",
    name: "질리언",
    tags: ["Support", "Mage"],
    partype: "마나",
    stats: {
      hp: 574,
      hpperlevel: 96,
      mp: 452,
      mpperlevel: 50,
      movespeed: 335,
      armor: 24,
      armorperlevel: 5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 5.5,
      hpregenperlevel: 0.5,
      mpregen: 11.35,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 52,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2.13,
      attackspeed: 0.625,
    },
  },
  {
    id: "Zoe",
    key: "142",
    name: "조이",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 630,
      hpperlevel: 106,
      mp: 425,
      mpperlevel: 25,
      movespeed: 340,
      armor: 21,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 7.5,
      hpregenperlevel: 0.6,
      mpregen: 8,
      mpregenperlevel: 0.65,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 2.5,
      attackspeed: 0.625,
    },
  },
  {
    id: "Zyra",
    key: "143",
    name: "자이라",
    tags: ["Mage", "Support"],
    partype: "마나",
    stats: {
      hp: 574,
      hpperlevel: 93,
      mp: 418,
      mpperlevel: 25,
      movespeed: 340,
      armor: 29,
      armorperlevel: 4.2,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 575,
      hpregen: 5.5,
      hpregenperlevel: 0.5,
      mpregen: 13,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 53,
      attackdamageperlevel: 3.2,
      attackspeedperlevel: 2.11,
      attackspeed: 0.681,
    },
  },
];
export default allChamps;
